--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyFactions
branches:
  - master
projects:
  PiggyFactions:
    path: ""
    icon: "resources/PiggyFactions-icon.png"
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.1.0
      - src: poggit/libasynql/libasynql
        version: ^4.2.0
      - src: SOF3/await-generator/await-generator
        version: ^3.6.1
      - src: AID-LEARNING/FormAPI/libFormAPI
        version: ^2.1.0
      - src: AID-LEARNING/IconForm/libIconForm
        version: ^1.0.0
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.2
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint: false
...
